domain: jp.ubuntu.com

image: prod-comms.ps5.docker-registry.canonical.com/jp.ubuntu.com

useProxy: false
readinessPath: "/"

env:
  - name: SENTRY_DSN
    value: https://5d270c51e9a946b6ae1bb0155498738d@sentry.is.canonical.com//12

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: ubuntu-api-key
      name: discourse-api

  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: ubuntu-api-username
      name: discourse-api

# Overrides for production
production:
  replicas: 5
  routes:
    - paths: [/blog]
      name: jp-ubuntu-com-blog
      app_name: jp.ubuntu.com-blog
      image: prod-comms.ps5.docker-registry.canonical.com/jp.ubuntu.com
      replicas: 3
      memoryLimit: 256Mi
      env:
        - name: DISCOURSE_API_KEY
          secretKeyRef:
            key: ubuntu-api-key
            name: discourse-api

        - name: DISCOURSE_API_USERNAME
          secretKeyRef:
            key: ubuntu-api-username
            name: discourse-api

        - name: SENTRY_DSN
          value: https://5d270c51e9a946b6ae1bb0155498738d@sentry.is.canonical.com//12

  nginxConfigurationSnippet: |
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  

# Overrides for staging
staging:
  replicas: 3
  routes:
    - paths: [/blog]
      name: jp-ubuntu-com-blog
      app_name: jp.ubuntu.com-blog
      image: prod-comms.ps5.docker-registry.canonical.com/jp.ubuntu.com
      replicas: 3
      memoryLimit: 256Mi
      env:
        - name: DISCOURSE_API_KEY
          secretKeyRef:
            key: ubuntu-api-key
            name: discourse-api

        - name: DISCOURSE_API_USERNAME
          secretKeyRef:
            key: ubuntu-api-username
            name: discourse-api

        - name: SENTRY_DSN
          value: https://5d270c51e9a946b6ae1bb0155498738d@sentry.is.canonical.com//12

  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
